05 images
IP777/nodejs-homework pull request #6
Opened 2020-08-15 08:19 UTC by IP777

2020-08-17 07:45 UTC, odykyi commented on api/middleware/avatarGenerator.js
> +			fs.writeFileSync(FOLDER + NAME, buffer);
use fs.promises

and do not use fs sync methods like writeFileSync readFileSync

2020-08-17 07:45 UTC, odykyi requested changes
comments

2020-08-17 13:21 UTC, IP777 commented on api/middleware/avatarGenerator.js
> +			fs.writeFileSync(FOLDER + NAME, buffer);
Пофиксил

2020-08-18 06:13 UTC, odykyi approved these changes

2020-08-18 06:13 UTC, merged